import React,{useState,useEffect} from 'react';import {View,Text,TextInput,TouchableOpacity,FlatList,StyleSheet,Alert,Modal,ScrollView} from 'react-native';import AsyncStorage from '@react-native-async-storage/async-storage';import {BarCodeScanner} from 'expo-barcode-scanner';
export default function App(){
const [p,setP]=useState([]),[n,setN]=useState(''),[b,setB]=useState(''),[s,setS]=useState(''),[q,setQ]=useState(''),[c,setC]=useState(''),[sz,setSz]=useState(''),[sales,setSales]=useState([]),[scan,setScan]=useState(false),[se,setSe]=useState(''),[tab,setTab]=useState('stock'),[show,setShow]=useState(false);
useEffect(()=>{load();},[]);
const load=async()=>{const a=await AsyncStorage.getItem('p29');const bb=await AsyncStorage.getItem('s29');if(a)setP(JSON.parse(a));if(bb)setSales(JSON.parse(bb));};
const save=async(d)=>{setP(d);await AsyncStorage.setItem('p29',JSON.stringify(d));};
const add=()=>{if(!n||!s)return Alert.alert('ناقص');const np={id:Date.now().toString(),name:n,buy:parseFloat(b)||0,sell:parseFloat(s),qty:parseInt(q)||1,bar:c,size:sz};save([...p,np]);setN('');setB('');setS('');setQ('');setC('');setSz('');setShow(false);};
const sell=(it)=>{if(it.qty<=0)return;const np=p.map(x=>x.id===it.id?{...x,qty:x.qty-1}:x);save(np);const ns=[...sales,{...it,saleId:Date.now(),profit:it.sell-it.buy}];setSales(ns);AsyncStorage.setItem('s29',JSON.stringify(ns));};
const totV=sales.reduce((a,b)=>a+b.sell,0),totB=sales.reduce((a,b)=>a+b.profit,0),filt=p.filter(x=>x.name.toLowerCase().includes(se.toLowerCase())||x.bar.includes(se));
const onScan=({data})=>{setScan(false);setSe(data);const f=p.find(x=>x.bar===data);if(!f){setC(data);setShow(true);}};
if(scan)return(<View style={{flex:1}}><BarCodeScanner onBarCodeScanned={onScan} style={StyleSheet.absoluteFill}/><TouchableOpacity onPress={()=>setScan(false)} style={{position:'absolute',bottom:50,alignSelf:'center',backgroundColor:'red',padding:15,borderRadius:10}}><Text style={{color:'white'}}>اغلاق</Text></TouchableOpacity></View>);
return(<View style={st.con}><View style={st.h}><Text style={st.logo}>MR MOUNTAIN TUNISIA V30</Text><Text style={st.sub}>V1-V29 ULTIMATE</Text></View><View style={st.tabs}><TouchableOpacity onPress={()=>setTab('stock')} style={[st.tab,tab==='stock'&&st.tabA]}><Text>مخزن</Text></TouchableOpacity><TouchableOpacity onPress={()=>setTab('caisse')} style={[st.tab,tab==='caisse'&&st.tabA]}><Text>صندوق</Text></TouchableOpacity></View><View style={{flexDirection:'row',padding:10}}><TextInput placeholder="بحث..." style={st.sea} value={se} onChangeText={setSe}/><TouchableOpacity onPress={()=>setScan(true)} style={st.sc}><Text>📷</Text></TouchableOpacity></View>{tab==='caisse'?<View style={{padding:15}}><Text style={{fontWeight:'bold',fontSize:18}}>الصندوق V21-V29</Text><View style={st.card}><Text>مبيعات: {totV} DT</Text></View><View style={st.card}><Text>ربح: {totB} DT</Text></View><View style={st.card}><Text>منتجات: {p.length}</Text></View></View>:<FlatList data={filt} keyExtractor={i=>i.id} renderItem={({item})=>{return(<View style={st.item}><View style={{flex:1}}><Text style={{fontWeight:'bold'}}>{item.name} {item.size}</Text><Text>شراء:{item.buy} بيع:{item.sell} كمية:{item.qty}</Text></View><TouchableOpacity onPress={()=>sell(item)} style={st.sell}><Text style={{color:'white'}}>بيع</Text></TouchableOpacity></View>)}}/>}<TouchableOpacity onPress={()=>setShow(true)} style={st.fab}><Text style={{color:'white',fontSize:30}}>+</Text></TouchableOpacity><Modal visible={show} animationType="slide"><ScrollView style={{padding:20,marginTop:30}}><Text style={{fontSize:20,fontWeight:'bold',marginBottom:15}}>اضافة منتج</Text><TextInput placeholder="اسم" value={n} onChangeText={setN} style={st.in}/><TextInput placeholder="مقاس" value={sz} onChangeText={setSz} style={st.in}/><TextInput placeholder="كود بار" value={c} onChangeText={setC} style={st.in}/><TextInput placeholder="شراء" value={b} onChangeText={setB} keyboardType="numeric" style={st.in}/><TextInput placeholder="بيع" value={s} onChangeText={setS} keyboardType="numeric" style={st.in}/><TextInput placeholder="كمية" value={q} onChangeText={setQ} keyboardType="numeric" style={st.in}/><TouchableOpacity onPress={add} style={st.btn}><Text style={{color:'white',textAlign:'center'}}>حفظ ✅</Text></TouchableOpacity><TouchableOpacity onPress={()=>setShow(false)} style={{marginTop:10}}><Text style={{textAlign:'center',color:'red'}}>الغاء</Text></TouchableOpacity></ScrollView></Modal></View>);}
const st=StyleSheet.create({con:{flex:1,backgroundColor:'#f5f5f5',paddingTop:35},h:{backgroundColor:'black',padding:15,alignItems:'center'},logo:{color:'#FFD700',fontWeight:'bold'},sub:{color:'white',fontSize:10},tabs:{flexDirection:'row',justifyContent:'space-around',backgroundColor:'white',padding:10},tab:{padding:10,borderRadius:10,backgroundColor:'#eee'},tabA:{backgroundColor:'#FFD700'},sea:{flex:1,backgroundColor:'white',borderRadius:10,padding:12,borderWidth:1},sc:{backgroundColor:'black',width:50,justifyContent:'center',alignItems:'center',borderRadius:10,marginLeft:8},item:{backgroundColor:'white',margin:8,padding:12,borderRadius:10,flexDirection:'row'},sell:{backgroundColor:'green',padding:10,borderRadius:8},fab:{position:'absolute',bottom:20,right:20,backgroundColor:'black',width:60,height:60,borderRadius:30,justifyContent:'center',alignItems:'center'},in:{backgroundColor:'white',padding:12,borderRadius:8,marginBottom:8,borderWidth:1},btn:{backgroundColor:'black',padding:15,borderRadius:10},card:{backgroundColor:'white',padding:15,borderRadius:10,marginTop:10}});
